### ISSUE TITLE
Add Vials of Entity Essence

### ISSUE THREAD

**Issue by 2008Choco** [2008Choco/Alchema#1]
# Vials of Essence
A new item may be added to better integrate Alchema with the world and the entities that inhabit it. This item should not be craftable in a crafting table but rather obtainable from entities through the means of a cauldron.

![Vials of entity essence in an inventory](https://i.imgur.com/7AWFikP.gif)

## How To Obtain Vials of Essence?
These essence vials may be obtained through three means:
- Boiling an entity in a cauldron to add a new type of ingredient, `alchema:entity_essence`
  * This ingredient may be used in a few new default crafting recipes. See below for potential new recipes
- Killing an entity with an empty vial (or a vial of the same type). Will only fill the vial partially (perhaps 5% for each kill?)
- As a very rare drop from entities

Empty vials are a new type of item craftable in a regular crafting table. See below:

![Crafting an empty vial](https://i.imgur.com/qTN3UUT.png)
![The empty vial](https://i.imgur.com/sI39Asv.png)

## What Do Vials of Essence Do?
As mentioned, vials of essence may be dropped into boiling cauldrons as an ingredient (`alchema:entity_essence`). The vials will hold a variable amount of essence (from 0 - 1,000) and will fill the cauldron accordingly. When not used in a cauldron, vials of essence may also be consumed by players much like a potion or bottle of water. Depending on the type of essence, the consumption will have differing effects on the player - whether those effects be positive or negative will also depend on the type of essence in the vial.

## Configuration
These new vials of essence should be relatively configurable for server owners. All potential configuration options may look like the following:

```yaml
VialOfEssence:
  MaximumEssence: 1000
  DroppedByEntities: true
  EssenceFromEntityKill: 50
  Item:
    Empty:
      Name: "&fEmpty Vial"
      Lore:
      - "Collects entity essence."
      CustomModelData: 1
    Filled:
      Name: "&fVial of Essence &7(%entity%)"
      Lore:
      - "&7&oCauldron ingredient"
      CustomModelData: 2
```

## Custom Textures?
By default, Alchema will not provide authors with any custom textures. The colours of the potions should suffice for at least the sake of vanilla and distinguishing between the differing types of essence. However, textures should be supported through the use of a customizable `CustomModelData` configuration option as seen in the Configuration section above.
